# Westerosi names, titles, and heraldic terms that typos mistakes for English misspellings.
[default.extend-words]
arry = "arry"
damon = "damon"
harras = "harras"
lew = "lew"
mormonts = "mormonts"
ned = "ned"
noy = "noy"
otho = "otho"
paly = "paly"
quitted = "quitted"
ser = "ser"
thenn = "thenn"
togglable = "togglable"
trys = "trys"
uffering = "uffering"
whent = "whent"
woh = "woh"
