export const SIGIL_SLUGS = new Set([
  "stark",
  "lannister",
  "targaryen",
  "baratheon",
  "greyjoy",
  "tully",
  "arryn",
  "martell",
  "tyrell",
  "bolton",
  "frey",
  "mormont",
  "umber",
  "karstark",
  "reed",
  "hightower",
  "velaryon",
  "tarly",
  "blackwood",
  "bracken",
  "dayne",
  "yronwood",
  "royce",
  "corbray",
  "redwyne",
  "florent",
  "rowan",
  "roxton",
  "oakheart",
  "mallister",
  "piper",
  "manderly",
  "dustin",
  "ryswell",
  "hornwood",
  "cerwyn",
  "blackfyre",
  "bar-emmon",
  "cargyll",
  "caswell",
  "celtigar",
  "chester",
  "crakehall",
  "glover",
  "peake",
  "reyne",
  "selmy",
  "wyl",
  "swann",
  "dondarrion",
  "caron",
  "estermont",
  "grafton",
  "tarth",
  "durrandon",
  "webber",
  "osgrey",
  "qorgyle",
  "allyrion",
  "banefort",
  "beesbury",
  "connington",
  "hoare",
  "marbrand",
  "stokeworth",
  "whent",
  "strong",
  "ashford",
  "hardyng",
  "freefolk",
  "fossoway-cider-hall",
  "fossoway-new-barrel",
  "duncan-the-tall",
  "clegane",
  "payne",
  "tarbeck",
  "dalt",
  "darklyn",
  "darry",
  "staunton",
  "tallhart",
  "harroway",
  "lothston",
  "mooton",
  "poole",
  "fisher",
  "gardener",
  "greyiron",
  "hollard",
  "mudd",
  "qoherys",
  "towers",
  "toyne",
  "ball",
  "blackmont",
  "fowler",
  "morrigen",
  "trant",
  "uller",
  "bronn",
  "belmore",
  "blount",
  "brax",
  "buckler",
  "bulwer",
  "cassel",
  "costayne",
  "manwoody",
  "hunter",
  "nights-watch",
  "rosby",
  "westerling",
  "baelish",
  "blacktyde",
  "cole",
  "farwynd",
  "goodbrother",
  "harlaw",
  "orkwood",
  "shett",
  "sunderland",
  "waynewood",
  "locke",
  "ambrose",
  "andrik-southshield",
  "belgrave",
  "bigglestone",
  "blackbar",
  "borrell",
  "bourney",
  "brune-dyre-den",
  "chambers",
  "charlton",
  "massey",
  "others",
  "unknown",
]);

const REGION_FILE: Record<string, string> = {
  north: "the-north",
  vale: "the-vale",
  riverlands: "the-riverlands",
  westerlands: "westerlands",
  reach: "the-reach",
  stormlands: "stormlands",
  dorne: "dorne",
  "iron-islands": "iron-islands",
  crownlands: "crownlands",
};

const SLUG_ALIASES: Record<string, string> = {
  durrandon: "baratheon",
  bronn: "blackwater",
  unknown: "unknown-westeros",
};

export function sigilFile({
  slug,
  region,
}: {
  slug: string;
  region?: string | null;
}): string {
  if (SIGIL_SLUGS.has(slug)) return SLUG_ALIASES[slug] ?? slug;
  if (region && REGION_FILE[region]) return REGION_FILE[region];
  return "unknown-westeros";
}
